### ISSUE TITLE
Alerting at end of action

### ISSUE THREAD

**Issue by Michelle-Ward** [ecomm-Labs/catwalk#37]
https://github.com/ecomm-Labs/catwalk/blob/84bcf1d41f564d28d09670d5f97a5eb3b712c8f7/client/src/components/Overview/Subcomponents/AddToCart.jsx#L104

soft suggestion- could utilize a component to create an "alert" letting the user know what has been added without disrupting user flow

**Comment by willtrinh** [comment]
Remove alert for now. If I have time later, would definitely make a notification component to handle click event.
