### ISSUE TITLE
logic inside of render function

### ISSUE THREAD

**Issue by Michelle-Ward** [ecomm-Labs/catwalk#52]
https://github.com/ecomm-Labs/catwalk/blob/84bcf1d41f564d28d09670d5f97a5eb3b712c8f7/client/src/components/Ratings/children/ReviewsList.jsx#L113

There are very large chunks of logic in this conditional. Would it be possible to break them down into their own functions. Also if we are checking for the results list to exist, would it be better to have the condition wrapping the component where it is declared in the parent that will pass the result list prop to it.

**Comment by sgasser94** [comment]
I have moved the sorting and filtering algorithms into their own methods of the ReviewList component. The conditional rendering of a button based on slicing of the reviews list is still done in the render method.
