### ISSUE TITLE
Seperation of concerns- large component

### ISSUE THREAD

**Issue by Michelle-Ward** [ecomm-Labs/catwalk#59]
https://github.com/ecomm-Labs/catwalk/blob/c3601aad3caf1a64859272a78cea72a1830c32ac/client/src/components/Overview/Subcomponents/ImageGallery.jsx#L85-L156

This component could be broken down into smaller parts between a selected image component and a list of images component.

**Comment by willtrinh** [comment]
Broken down ExtendedView for ImageGallery into another component
